# if you update this file, please consider updating Vagrantfile too

language: cpp


env:
  global:
    - CCACHE_CPP2=1
    - JOBS=4
    - QT_FATAL_WARNINGS=1
    - SHADOW_BUILD_DIR=/tmp/shadow_build_dir

    - QT_SHORT_VERSION=5.9
    - QT_FULL_VERSION=${QT_SHORT_VERSION}.3

    - LINUX_SPEC=linux-g++-64
    - OSX_SPEC=macx-clang

    - GCC_VERSION=7
    - GXX_VERSION=${GCC_VERSION}

    - CACHE_DIR=/tmp/qtcache


matrix:
    fast_finish: true
    include:
        # Release jobs
        - os: linux
          dist: trusty
          env: SPEC="${LINUX_SPEC}" CONFIG=installer
          sudo: required

        - os: osx
          osx_image: xcode9
          env: SPEC="${OSX_SPEC}" CONFIG=installer
          sudo: required

        # Debug jobs
        - os: linux
          dist: trusty
          env: SPEC="${LINUX_SPEC}" CONFIG=debug
          sudo: required
          if: branch =~ ^wip OR branch =~ ^pr-

        - os: osx
          osx_image: xcode9
          env: SPEC="${OSX_SPEC}" CONFIG=debug
          sudo: required
          if: branch =~ ^wip OR branch =~ ^pr-


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - ccache
      - espeak
      - libespeak-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-0:amd64
      - libgstreamer1.0-dev
      - libsdl2-dev
      - libudev-dev
      - wget
      - libusb-1.0.0-dev
      - libblkid-dev
      - liblzma-dev


cache:
  directories:
    - $HOME/.ccache
    - ${CACHE_DIR}


before_install:
  # fetch entire git repo to properly determine the version
  - if [ "${CONFIG}" = "installer" ]; then
        cd ${TRAVIS_BUILD_DIR} && git fetch --unshallow && git fetch --all --tags;
    fi

  # compile threads
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        export JOBS=$((`cat /proc/cpuinfo | grep -c ^processor`+1));
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        export JOBS=$((`sysctl -n hw.ncpu`+1));
    fi

  # clouds urls
  - export QGC_CLOUD="https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies"
  - export QT_CLOUD="http://files.emlid.com/qgc/Qt"
  

  # qt names
  - export QT_FOLDER_NAME="Qt${QT_FULL_VERSION}-${SPEC}"
  - export QT_PACKAGE_NAME="${QT_FOLDER_NAME}.tar.bz2"

  - export QT_DIR="/tmp/${QT_FOLDER_NAME}/${SPEC}/"

  # general paths
  - export QT_QPA_PLATFORM_PLUGIN_PATH="${QT_DIR}/plugins"
  - export QML2_IMPORT_PATH="${QT_DIR}/qml"
  - export PATH="${QT_DIR}/bin:$PATH"


install:
  # Check for Qt cache
  - if [ -z "$(ls -A ${CACHE_DIR} 2>&-)" ]; then
        echo "Qt cache not found. Downloading from cloud..." &&
        mkdir -p "${CACHE_DIR}" && cd "${CACHE_DIR}" &&
        wget "${QT_CLOUD}/${QT_PACKAGE_NAME}" &&
        cd -
        ;
    fi
  - tar -jxf "${CACHE_DIR}/${QT_PACKAGE_NAME}" -C /tmp

  # linux exports 
  - if [ "${SPEC}" = "${LINUX_SPEC}" ]; then
        sudo apt-get update &&
        sudo apt-get install g++-${GXX_VERSION} gcc-${GCC_VERSION} &&

        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GXX_VERSION} 90 &&
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 90 &&

        export CXX=g++-${GXX_VERSION} &&
        export CC=gcc-${GCC_VERSION} &&
        export DISPLAY=:99.0 &&

        sh -e /etc/init.d/xvfb start
        ;
    fi

  - if [ "${SPEC}" = "${OSX_SPEC}" ]; then
        brew update && brew install xz ccache &&

        GSTRMR_PKG="gstreamer-1.0-1.5.2-x86_64.pkg" &&
        GSTRMR_DEV_PKG="gstreamer-1.0-devel-1.5.2-x86_64.pkg" &&
        OSX_GSTRMR="osx-gstreamer.tar.bz2" &&

        wget "${QGC_CLOUD}/${GSTRMR_PKG}" &&
        wget "${QGC_CLOUD}/${GSTRMR_DEV_PKG}" &&
        wget "${QGC_CLOUD}/${OSX_GSTRMR}" &&

        sudo installer -verboseR -pkg "${GSTRMR_PKG}"     -target / &&
        sudo installer -verboseR -pkg "${GSTRMR_DEV_PKG}" -target / &&
        sudo tar jxf "${OSX_GSTRMR}" -C /Library/Frameworks
        ;
    fi
  
  # print ccache stats
  - ccache -s


before_script:
  # grab latest PX4 parameter and airframe metadata
  - PX4_PARAMS_CLOUD="http://px4-travis.s3.amazonaws.com/Firmware/master"
  - wget ${PX4_PARAMS_CLOUD}/parameters.xml -O src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml
  - wget ${PX4_PARAMS_CLOUD}/airframes.xml  -O src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml


script:
  # run qmake
  - mkdir "${SHADOW_BUILD_DIR}" && cd "${SHADOW_BUILD_DIR}"
  - qmake -r "${TRAVIS_BUILD_DIR}/qgroundcontrol.pro" CONFIG+=${CONFIG} -spec ${SPEC}

  # compile
  - make -j$JOBS;


before_deploy:
  # create linux appimage
  # export QGC package dir for deploying

  - BUILD_TYPE="${CONFIG//installer/release}"
  - QGC_APP_DIR="${SHADOW_BUILD_DIR}/${BUILD_TYPE}"
  - export QGC_PKG_DIR="${QGC_APP_DIR}/package"

  - cd "${TRAVIS_BUILD_DIR}" && mkdir -p "${QGC_PKG_DIR}"

  - if [[ "${SPEC}" = "${LINUX_SPEC}" ]]; then
      ./deploy/create_linux_appimage.sh "${TRAVIS_BUILD_DIR}" "${QGC_APP_DIR}" "${QGC_PKG_DIR}" &&
      mv "${QGC_PKG_DIR}/QGroundControl.AppImage" "${QGC_PKG_DIR}/QGroundControl-${BUILD_TYPE}.AppImage"
      ;
    fi

  # make tarball with OSX debug app
  # - if [[ "${SPEC}" = "${OSX_SPEC}" && "${CONFIG}" = "debug" ]]; then
  #      tar -cjf "${QGC_PKG_DIR}/QGroundControl.app.tar.bz2" "${QGC_APP_DIR}/QGroundControl.app"
  #      ;
  #   fi 

deploy:
  provider: releases
  api_key:
    secure: O7iuimgYBMdySJNQV/+4D1GxPDWHTphE7RnK3U/i7n/FbXNBhATZRRKGFpwbB0U9GOfOBCDmzZ+6Ybst75dAwuwmIeNb4TSFDM4zt2o11ZtgEhrcxVk84XH18jFtpjzlqqvmrGOv2YaknbR+g2EKL9fNyWhTmjx96MxV9P9Hou47mnli2QFDyyTbb5Gv/cDYH1mDFJ9psnezYig0b/bmVn2QvFqB3t1Sbbryjtv2OXix8+Ns+yzSwcNDcpUWjeWW2+4DeXF3brM8y4Wc5SvPXekbaD+mn4S7E4QcnbX1w4fu6goPNCzaGLirMewfjgrQWhKWY6pwhJqGMX2mjrNjf4XrW2igfytYN5otJfmjubm/lASHEJvYlGK3gWQhdsErszUqXxGeAjfe8cCAWuvJPHwbqn+fjIufD7sD73TFcSMP0AL5/gNtcktek/OzE7p2r3FhdxlD56p2109EmMlCW9r9a8S+AOBgwF17pZbaDQOzsQkQF8veq+z2NaffdXDBr3OLAwcZhkZTTdtA32nt8BQgg6je5k7cMOnxVswGcODXFRTds7J+5Z3OOlKXM9RBRwnFTqz7isfyw3dJvq8wNK/5qIGQZzzZk3qdMVK5ciu2XtL5fp2g2n1mgW2weG2DdYF93MU8HzkmWYOkwkLw3UPqy591CRiwq1mb9yxmemA=
  file_glob: true
  file: ${QGC_PKG_DIR}/*
  skip_cleanup: true
  on:
    tags: true
    condition: $CONFIG = installer
